{"name": "test_check_values[9-Not in range]", "status": "passed", "attachments": [{"name": "log", "source": "3cd49ab3-26e2-4fb1-a33a-45b553f2b8c0-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "value", "value": "'9'"}, {"name": "error_msg", "value": "'Not in range'"}], "start": 1708022558546, "stop": 1708022558727, "uuid": "a0806a96-3e44-4f10-9669-8f590c09308c", "historyId": "c8f05572fbc580c5d918962a1b5aa017", "testCaseId": "c86d3f30a0580e22e859abbb442500ba", "fullName": "tests.test_check_and_validate#test_check_values", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_check_and_validate"}, {"name": "host", "value": "DESKTOP-EU8NHV5"}, {"name": "thread", "value": "5728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_check_and_validate"}]}