{"name": "test_check_values[9-Not in range]", "status": "passed", "attachments": [{"name": "log", "source": "dce168b5-57c0-47e0-aa8e-04fdd68ce419-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "value", "value": "'9'"}, {"name": "error_msg", "value": "'Not in range'"}], "start": 1708103329292, "stop": 1708103329498, "uuid": "49a4a9b3-11cb-4cce-88c4-9c4647265606", "historyId": "c8f05572fbc580c5d918962a1b5aa017", "testCaseId": "c86d3f30a0580e22e859abbb442500ba", "fullName": "tests.test_check_and_validate#test_check_values", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_check_and_validate"}, {"name": "host", "value": "DESKTOP-EU8NHV5"}, {"name": "thread", "value": "8996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_check_and_validate"}]}