{"name": "test_check_values[51-Not in range]", "status": "passed", "attachments": [{"name": "log", "source": "956bdb46-4cae-4245-8e03-83af93e3300a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "value", "value": "'51'"}, {"name": "error_msg", "value": "'Not in range'"}], "start": 1708022568798, "stop": 1708022568953, "uuid": "499351f9-2857-4fbb-9871-aaeaff13caab", "historyId": "fe6f6a3dcf43c2082fd32411e48d1c45", "testCaseId": "c86d3f30a0580e22e859abbb442500ba", "fullName": "tests.test_check_and_validate#test_check_values", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_check_and_validate"}, {"name": "host", "value": "DESKTOP-EU8NHV5"}, {"name": "thread", "value": "5728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_check_and_validate"}]}