{"name": "test_check_values[51-Not in range]", "status": "passed", "attachments": [{"name": "log", "source": "b89a3f5f-dc27-4e88-a578-c023605084f3-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "value", "value": "'51'"}, {"name": "error_msg", "value": "'Not in range'"}], "start": 1708179222554, "stop": 1708179222745, "uuid": "108133bf-4ce0-45fc-a812-1943db121128", "historyId": "fe6f6a3dcf43c2082fd32411e48d1c45", "testCaseId": "c86d3f30a0580e22e859abbb442500ba", "fullName": "tests.test_check_and_validate#test_check_values", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_check_and_validate"}, {"name": "host", "value": "DESKTOP-EU8NHV5"}, {"name": "thread", "value": "9776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_check_and_validate"}]}