{"name": "test_check_values[9-Not in range]", "status": "passed", "attachments": [{"name": "log", "source": "f7da578a-a628-4c75-b471-12a3bb689998-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "value", "value": "'9'"}, {"name": "error_msg", "value": "'Not in range'"}], "start": 1708179210659, "stop": 1708179210909, "uuid": "0b360b98-24a9-4431-8429-24474fe83c04", "historyId": "c8f05572fbc580c5d918962a1b5aa017", "testCaseId": "c86d3f30a0580e22e859abbb442500ba", "fullName": "tests.test_check_and_validate#test_check_values", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_check_and_validate"}, {"name": "host", "value": "DESKTOP-EU8NHV5"}, {"name": "thread", "value": "9776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_check_and_validate"}]}